# Generated by Django 5.2.7 on 2025-11-18 00:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('name', models.CharField(help_text='Nombre único del rol (ej: administrador, doctor)', max_length=50, unique=True, verbose_name='Nombre del rol')),
                ('slug', models.SlugField(help_text='Identificador en minúsculas sin espacios', unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, help_text='Descripción detallada del rol y sus responsabilidades', verbose_name='Descripción')),
                ('can_manage_users', models.BooleanField(default=False, help_text='Crear, editar y eliminar usuarios del sistema', verbose_name='Gestionar usuarios')),
                ('can_manage_doctors', models.BooleanField(default=False, help_text='Administrar perfiles de doctores y especialidades', verbose_name='Gestionar doctores')),
                ('can_view_all_appointments', models.BooleanField(default=False, help_text='Acceso a todas las citas del sistema', verbose_name='Ver todas las citas')),
                ('can_manage_schedules', models.BooleanField(default=False, help_text='Configurar horarios y disponibilidad de doctores', verbose_name='Gestionar horarios')),
                ('can_view_medical_records', models.BooleanField(default=False, help_text='Acceso a historiales médicos de pacientes', verbose_name='Ver historiales médicos')),
                ('can_create_prescriptions', models.BooleanField(default=False, help_text='Emitir recetas médicas', verbose_name='Crear recetas')),
                ('can_manage_patients', models.BooleanField(default=False, help_text='Crear, editar y ver información de pacientes', verbose_name='Gestionar pacientes')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el rol está activo en el sistema', verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'db_table': 'roles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID público')),
                ('email', models.EmailField(help_text='Email único para autenticación', max_length=255, unique=True, verbose_name='Correo electrónico')),
                ('username', models.CharField(help_text='Username único para el sistema', max_length=150, unique=True, verbose_name='Nombre de usuario')),
                ('first_names', models.CharField(blank=True, help_text='Nombres completos del usuario', max_length=255, verbose_name='Nombres')),
                ('last_names', models.CharField(blank=True, help_text='Apellidos completos del usuario', max_length=255, verbose_name='Apellidos')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el usuario puede acceder al sistema', verbose_name='Activo')),
                ('is_staff', models.BooleanField(default=False, help_text='Permite acceso al panel de administración de Django', verbose_name='Es staff')),
                ('is_superuser', models.BooleanField(default=False, help_text='Otorga todos los permisos sin asignarlos explícitamente', verbose_name='Es superusuario')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='Último acceso')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('role', models.ForeignKey(blank=True, help_text='Rol que determina los permisos del usuario', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='users.role', verbose_name='Rol')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'users',
                'indexes': [models.Index(fields=['uuid'], name='idx_user_uuid'), models.Index(fields=['email'], name='idx_user_email'), models.Index(fields=['role'], name='idx_user_role')],
            },
        ),
    ]
