# Generated by Django 5.2.7 on 2025-11-18 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Indica si el usuario puede acceder al sistema. El administrador debe activarlo manualmente.', verbose_name='Activo'),
        ),
    ]
