# Generated by Django 5.2.7 on 2026-02-02 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessInfo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('ruc', models.CharField(help_text='RUC del negocio para consultar en el SRI (13 dígitos)', max_length=13, unique=True, verbose_name='RUC')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Información del Negocio',
                'verbose_name_plural': 'Información del Negocio',
                'db_table': 'business_info',
            },
        ),
    ]
