# Generated by Django 5.2.7 on 2026-02-03 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sequential',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('ruc', models.CharField(help_text='RUC del emisor (13 dígitos)', max_length=13, verbose_name='RUC')),
                ('establishment_code', models.CharField(help_text='Código del establecimiento (3 dígitos, ej: 001)', max_length=3, verbose_name='Código de Establecimiento')),
                ('point_code', models.CharField(help_text='Código del punto de emisión (3 dígitos, ej: 001)', max_length=3, verbose_name='Código de Punto de Emisión')),
                ('document_type', models.CharField(choices=[('01', 'Factura'), ('03', 'Liquidación de compra'), ('04', 'Nota de crédito'), ('05', 'Nota de débito'), ('06', 'Guía de remisión'), ('07', 'Comprobante de retención')], default='01', help_text='Código del tipo de documento', max_length=2, verbose_name='Tipo de Documento')),
                ('last_sequential', models.IntegerField(default=0, help_text='Último número secuencial generado (sin importar si se usó o no)', verbose_name='Último Secuencial Generado')),
            ],
            options={
                'verbose_name': 'Secuencial',
                'verbose_name_plural': 'Secuenciales',
                'db_table': 'sequentials',
                'ordering': ['ruc', 'establishment_code', 'point_code', 'document_type'],
                'unique_together': {('ruc', 'establishment_code', 'point_code', 'document_type')},
            },
        ),
        migrations.CreateModel(
            name='SequentialUsage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('sequential_number', models.IntegerField(help_text='Número secuencial específico', verbose_name='Número Secuencial')),
                ('status', models.CharField(choices=[('available', 'Disponible'), ('pending', 'Pendiente'), ('used', 'Usado')], default='pending', max_length=10, verbose_name='Estado')),
                ('sequential', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='core.sequential', verbose_name='Secuencial')),
            ],
            options={
                'verbose_name': 'Uso de Secuencial',
                'verbose_name_plural': 'Usos de Secuenciales',
                'db_table': 'sequential_usages',
                'ordering': ['sequential', 'sequential_number'],
                'indexes': [models.Index(fields=['sequential', 'status'], name='sequential__sequent_c88284_idx')],
                'unique_together': {('sequential', 'sequential_number')},
            },
        ),
    ]
