# Generated by Django 5.2.7 on 2026-02-03 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sequential_sequentialusage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sequential',
            options={'verbose_name': 'Secuencial', 'verbose_name_plural': 'Secuenciales'},
        ),
        migrations.AlterUniqueTogether(
            name='sequential',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='sequential',
            name='document_type',
        ),
        migrations.RemoveField(
            model_name='sequential',
            name='establishment_code',
        ),
        migrations.RemoveField(
            model_name='sequential',
            name='point_code',
        ),
        migrations.RemoveField(
            model_name='sequential',
            name='ruc',
        ),
    ]
