# Generated by Django 5.2.7 on 2026-02-03 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_sequential_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('description', models.CharField(help_text='Descripción del producto o servicio', max_length=255, verbose_name='Descripción')),
                ('code', models.CharField(help_text='Código único del producto', max_length=50, unique=True, verbose_name='Código')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Precio unitario del producto', max_digits=10, verbose_name='Precio Unitario')),
            ],
            options={
                'verbose_name': 'Producto/Servicio',
                'verbose_name_plural': 'Productos/Servicios',
                'db_table': 'products',
                'ordering': ['code'],
            },
        ),
    ]
