# Generated by Django 5.2.7 on 2025-11-19 05:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0002_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID público')),
                ('appointment_date', models.DateField(help_text='Día programado para la cita', verbose_name='Fecha de la cita')),
                ('appointment_time', models.TimeField(help_text='Hora programada para la cita', verbose_name='Hora de la cita')),
                ('duration_minutes', models.IntegerField(default=60, help_text='Duración estimada de la cita en minutos (por defecto 60)', verbose_name='Duración (minutos)')),
                ('status', models.CharField(choices=[('scheduled', 'Agendada'), ('confirmed', 'Confirmada'), ('in_progress', 'En Curso'), ('completed', 'Completada'), ('cancelled', 'Cancelada'), ('no_show', 'No Asistió')], default='scheduled', help_text='Estado actual de la cita', max_length=20, verbose_name='Estado')),
                ('notes', models.TextField(blank=True, help_text='Notas adicionales sobre la cita', verbose_name='Notas')),
                ('doctor_specialist', models.ForeignKey(help_text='Doctor y especialidad para la cita', on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='doctors.doctorspecialty', verbose_name='Doctor y Especialidad')),
                ('patient', models.ForeignKey(help_text='Paciente que solicita la cita', on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='patients.patient', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
                'db_table': 'appointments',
                'ordering': ['-appointment_date', '-appointment_time'],
                'indexes': [models.Index(fields=['uuid'], name='idx_appointment_uuid'), models.Index(fields=['patient', 'appointment_date'], name='idx_appt_patient_date'), models.Index(fields=['doctor_specialist', 'appointment_date'], name='idx_appt_doctor_date'), models.Index(fields=['status'], name='idx_appt_status'), models.Index(fields=['appointment_date', 'appointment_time'], name='idx_appt_datetime')],
            },
        ),
        migrations.CreateModel(
            name='BlockTimeSlot',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('date', models.DateField(help_text='Día del bloqueo', verbose_name='Fecha')),
                ('blocked_time', models.TimeField(help_text='Hora específica del bloqueo', verbose_name='Hora bloqueada')),
                ('reason', models.CharField(blank=True, help_text='Motivo del bloqueo (vacaciones, reunión, etc.)', max_length=500, verbose_name='Razón')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el bloqueo está activo', verbose_name='Activo')),
                ('blocked_by_user', models.ForeignKey(blank=True, help_text='Usuario que creó el bloqueo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocked_slots', to=settings.AUTH_USER_MODEL, verbose_name='Bloqueado por')),
                ('doctor', models.ForeignKey(help_text='Doctor cuyo horario se bloquea', on_delete=django.db.models.deletion.CASCADE, related_name='blocked_slots', to='doctors.doctor', verbose_name='Doctor')),
            ],
            options={
                'verbose_name': 'Bloqueo de Horario',
                'verbose_name_plural': 'Bloqueos de Horarios',
                'db_table': 'block_time_slots',
                'indexes': [models.Index(fields=['doctor', 'date'], name='idx_block_doctor_date'), models.Index(fields=['is_active'], name='idx_block_active')],
                'unique_together': {('doctor', 'date', 'blocked_time')},
            },
        ),
        migrations.CreateModel(
            name='DoctorSchedule',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], help_text='Día en que el doctor atiende', verbose_name='Día de la semana')),
                ('start_time', models.TimeField(help_text='Hora en que inicia la atención', verbose_name='Hora de inicio')),
                ('end_time', models.TimeField(help_text='Hora en que termina la atención', verbose_name='Hora de fin')),
                ('slot_duration_minutes', models.IntegerField(default=60, help_text='Duración de cada slot de cita en minutos (por defecto 60)', verbose_name='Duración del slot (minutos)')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si este horario está activo', verbose_name='Activo')),
                ('doctor', models.ForeignKey(help_text='Doctor al que pertenece este horario', on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='doctors.doctor', verbose_name='Doctor')),
            ],
            options={
                'verbose_name': 'Horario del Doctor',
                'verbose_name_plural': 'Horarios de Doctores',
                'db_table': 'doctor_schedule',
                'indexes': [models.Index(fields=['doctor', 'day_of_week'], name='idx_schedule_doctor_day'), models.Index(fields=['is_active'], name='idx_schedule_active')],
                'unique_together': {('doctor', 'day_of_week', 'start_time')},
            },
        ),
    ]
