# Generated by Django 5.2.7 on 2026-01-19 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Agendada'), ('confirmed', 'Confirmada'), ('completed', 'Completada'), ('cancelled', 'Cancelada'), ('no_show', 'No Asistió')], default='scheduled', help_text='Estado actual de la cita', max_length=20, verbose_name='Estado'),
        ),
    ]
