# Generated by Django 5.2.7 on 2025-11-18 00:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID público')),
                ('first_names', models.CharField(help_text='Nombres completos del paciente', max_length=255, verbose_name='Nombres')),
                ('last_names', models.CharField(help_text='Apellidos completos del paciente', max_length=255, verbose_name='Apellidos')),
                ('document_id', models.CharField(help_text='Cédula o documento único del paciente', max_length=10, unique=True, verbose_name='Documento de identidad')),
                ('email', models.EmailField(help_text='Correo electrónico para notificaciones', max_length=255, verbose_name='Email')),
                ('phone_number', models.CharField(help_text='Número de contacto del paciente', max_length=10, verbose_name='Teléfono')),
                ('address', models.CharField(help_text='Dirección de residencia', max_length=500, verbose_name='Dirección')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el paciente está activo en el sistema', verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'db_table': 'patients',
                'indexes': [models.Index(fields=['uuid'], name='idx_patient_uuid'), models.Index(fields=['document_id'], name='idx_patient_document'), models.Index(fields=['email'], name='idx_patient_email'), models.Index(fields=['is_active'], name='idx_patient_active')],
            },
        ),
    ]
