# Generated by Django 5.2.7 on 2025-11-19 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='address',
            field=models.CharField(blank=True, help_text='Dirección de residencia (opcional)', max_length=500, verbose_name='Dirección'),
        ),
    ]
