# Generated by Django 5.2.7 on 2025-11-18 00:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID público')),
                ('first_names', models.CharField(help_text='Nombres completos del doctor', max_length=255, verbose_name='Nombres')),
                ('last_names', models.CharField(help_text='Apellidos completos del doctor', max_length=255, verbose_name='Apellidos')),
                ('document_id', models.CharField(help_text='Cédula o documento único', max_length=10, unique=True, verbose_name='Documento de identidad')),
                ('email', models.EmailField(help_text='Email profesional del doctor', max_length=255, verbose_name='Email')),
                ('phone_number', models.CharField(help_text='Número de contacto', max_length=10, verbose_name='Teléfono')),
                ('address', models.CharField(help_text='Dirección de residencia o consultorio', max_length=500, verbose_name='Dirección')),
                ('biography', models.CharField(blank=True, help_text='Breve biografía profesional', max_length=255, verbose_name='Biografía')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el doctor está activo en el sistema', verbose_name='Activo')),
                ('hire_date', models.DateField(help_text='Fecha en que el doctor ingresó a la clínica', verbose_name='Fecha de contratación')),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctores',
                'db_table': 'doctors',
            },
        ),
        migrations.CreateModel(
            name='DoctorSpecialty',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('is_primary', models.BooleanField(default=False, help_text='Indica si es la especialidad principal del doctor', verbose_name='Es principal')),
            ],
            options={
                'verbose_name': 'Especialidad del Doctor',
                'verbose_name_plural': 'Especialidades de Doctores',
                'db_table': 'doctor_specialty',
            },
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('name', models.CharField(help_text='Nombre de la especialidad médica', max_length=255, unique=True, verbose_name='Nombre')),
                ('description', models.CharField(blank=True, help_text='Descripción breve de la especialidad', max_length=500, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si la especialidad está disponible', verbose_name='Activa')),
            ],
            options={
                'verbose_name': 'Especialidad',
                'verbose_name_plural': 'Especialidades',
                'db_table': 'specialties',
                'ordering': ['name'],
            },
        ),
    ]
