# Generated by Django 5.2.7 on 2025-11-18 00:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='user',
            field=models.OneToOneField(help_text='Usuario del sistema asociado al doctor', on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='doctorspecialty',
            name='doctor',
            field=models.ForeignKey(help_text='Doctor que tiene esta especialidad', on_delete=django.db.models.deletion.CASCADE, related_name='specialties', to='doctors.doctor', verbose_name='Doctor'),
        ),
        migrations.AddField(
            model_name='doctorspecialty',
            name='specialty',
            field=models.ForeignKey(help_text='Especialidad que practica el doctor', on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='doctors.specialty', verbose_name='Especialidad'),
        ),
        migrations.AddIndex(
            model_name='doctor',
            index=models.Index(fields=['uuid'], name='idx_doctor_uuid'),
        ),
        migrations.AddIndex(
            model_name='doctor',
            index=models.Index(fields=['document_id'], name='idx_doctor_document'),
        ),
        migrations.AddIndex(
            model_name='doctor',
            index=models.Index(fields=['is_active'], name='idx_doctor_active'),
        ),
        migrations.AddIndex(
            model_name='doctorspecialty',
            index=models.Index(fields=['doctor', 'is_primary'], name='idx_doctor_primary_spec'),
        ),
        migrations.AlterUniqueTogether(
            name='doctorspecialty',
            unique_together={('doctor', 'specialty')},
        ),
    ]
